platform: linux
inputs:
  - name: app-repo
outputs:
  - name: app-build
caches:
  - path: .npm
run:
  path: sh
  args:
    - -c
    - |
      set -ex
      cwd="$(pwd)"
      cp -faT app-repo app-prepared
      export npm_config_cache=".npm"
      npm set progress=false
      cd app-prepared
        npm install
        ls -al dapp/
      cd $cwd
      cp -fa app-prepared/Dockerfile app-build/
      cp -fa app-prepared/dapp/ app-build/
      mkdir -p app-build/.git/
      cp -fa app-prepared/.git/ref app-build/.git/
