platform: linux
inputs:
  - name: app-repo
outputs:
  - name: app-build
caches:
  - path: .npm
run:
  path: sh
  args:
    - -c
    - |
      set -ex
      cwd="$(pwd)"
      export npm_config_cache=".npm"
      npm set progress=false
      cd app-repo
        npm install
        ls -al dapp/
      cd $cwd
      cp -fa app-repo/Dockerfile app-build/
      cp -fa app-repo/dapp/ app-build/
      mkdir -p app-build/.git/
      cp -fa app-repo/.git/ref app-build/.git/
