platform: linux
inputs:
  - name: app-repo
outputs:
  - name: app-prepared
caches:
  - path: .npm
run:
  path: sh
  args:
    - -c
    - |
      set -ex
      cp -faT app-repo app-prepared
      export npm_config_cache="$(pwd)/.npm"
      export HUSKY_SKIP_INSTALL=true
      npm set progress=false
      cwd="$(pwd)"
      cd app-prepared
        npm ci
      cd "${cwd}"
