platform: linux
inputs:
  - name: app-repo
outputs:
  - name: app-prepared
caches:
  - path: .npm
run:
  path: sh
  args:
    - -c
    - |
      set -ex
      cwd="$(pwd)"
      export npm_config_cache=".npm"
      npm set progress=false
      npm set unsafe-perm true
      cd app-repo
        npm install
      cd $cwd
      cp -fa app-repo/Dockerfile app-prepared/
      cp -fa app-repo/dapp/ app-prepared/
      mkdir -p app-prepared/.git/
      cp -fa app-repo/.git/head_sha app-prepared/.git/ref
